AccountCenterPage:
  编辑: xpath //*[@id="app"]/div/div/div[2]/div/div/div/div/div[1]/div/div/div[1]/a/div

AccountEditPage:
  name: id name
  description: id description
  提交: xpath //*[@id="app"]/div/div/div[2]/div/div/div/div/div/div/div[2]/div[2]/div/form/div[3]/div/div/span/button
